### ISSUE TITLE
Function signatures for photometry functions

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#149]
The new photometry routines, like the old ones, have a fairly large number of required arguments. It would be nice to simplify that, by either grouping things into objects, or making them keyword arguments so that there is at least some indication in the function call what the arguments are.

Edit:

```[tasklist]
### Tasks
- [x] Provide a settings object for the arguments with defaults in photometry
- [x] Maybe make interface class-based
- [ ] Consolidate settings into a single settings object by composing the sub-settings
```
