### ISSUE TITLE
Rewrite the photometry settings widget in pydantic/ipyautoui, and add option to select Camera settings

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#166]
This will include several things:

```[tasklist]
### Tasks
- [x] Move the code from `gui_tools` to `settings`
- [x] Subclass from pydantic `BaseModel`, but include most of the methods that already exist
- [x] Autogenerate the UI
```

**Comment by mwcraig** [comment]
Decided not to worry about the camera settings for now.
