### ISSUE TITLE
Remove executable code from top level in tests

### ISSUE THREAD

**Issue by mwcraig** [feder-observatory/stellarphot#410]
One of the reasons that #408 wasn't caught earlier was that some of our test files execute some of our code on import, e.g. in places where we create a default camera. As it turns out, making a `Camera` fixes #408, so writing a test for it is...challenging.

It seems worth rewriting the tests a bit so that we are not running any of our code outside of tests functions and classes to avoid something like this happening in the future. 

```[tasklist]
### Tasks
- [ ] https://github.com/feder-observatory/stellarphot/issues/412
- [ ] https://github.com/feder-observatory/stellarphot/issues/413
- [ ] https://github.com/feder-observatory/stellarphot/issues/414
- [ ] https://github.com/feder-observatory/stellarphot/issues/416
```
