### ISSUE TITLE
Consider removing Feder specific code in stellarphot

### ISSUE THREAD

**Issue by JuanCab** [feder-observatory/stellarphot#98]
I poked around and identified the following places where the code either assumes or refers to Feder Observatory in the current version of `stellarphot`.  I found the following:

- [x] `photometry.py`
  - **Assumes only Feder!** `add_to_photometry_table()`: Turns out code only adds BJD field to `phot` if the observatory is Feder (lines 381-383: Codes for Feder Observatory BJD)
  - `find_times()`: latitude and longitude defaults to Feder (but does allow other choices)
- [x] `visualization/comparison_functions.py` is hardcoded for Feder!
  - [x] **Assumes only Feder!**  In `ComparisonViewer/_set_object` line 513 sets `telescope_code` for `tess_submission` to Feder
  - [x] **Assumes only Feder!**  In `ComparisonViewer/_make_tess_save_box` line 625 sets displayed telescope code to Feder, no other option.
- [x] `visualization/seeing_profile_functions.py` is hardcoded for Feder!
  -  [x] **Assumes only Feder!** In `SeeingProfileWidget/_make_tess_save_box` line 447 sets displayed telescope code to Feder, no other option.
  -  [x] **Assumes only Feder!** In `SeeingProfileWidget/_update_plots` the read noise and gain are set to the values for our camera (CG16M).
```[tasklist]
### Tasks
```

**Comment by JuanCab** [comment]
PR #141 and #145 have addressed the first bullet point.

**Comment by mwcraig** [comment]
> Assumes only Feder! In SeeingProfileWidget/_update_plots the read noise and gain are set to the values for our camera (CG16M).

This bit is done in #236

**Comment by mwcraig** [comment]
> Assumes only Feder! In SeeingProfileWidget/_make_tess_save_box line 447 sets displayed telescope code to Feder, no other option.

This is done in #268

**Comment by mwcraig** [comment]
>  `gui_tools/comparison_functions.py` is hardcoded for Feder!

This is also done in #268 now
